### PR TITLE
Add police-force and police-neighbourhood to discovery

### PR DESCRIPTION
**Pull request by fjavierm**

### CODE REVIEW

**Comment by elliecraven** [comment]
should this be police-force, not policy-force?

**Comment by michaelabenyohai** [comment]
This looks fine but you will also need to create a PR for this bit - https://github.com/openregister/deployment#6-update-terraform-config. I'm happy to approve this one and you raise another, or you can add both to this PR and I will approve this one?

**Comment by fjavierm** [comment]
@michaelabenyohai I was going to create another PR but, everything is here now

**Comment by michaelabenyohai** [comment]
Sorry! I will just approve next time!

**Comment by fjavierm** [comment]
@michaelabenyohai  No worries, it was a fair question :)

**Pull request merged**
