### PR TITLE
Use the latest Amazon Linux AMI

### PR DESCRIPTION
**Pull request by samcrang**
https://github.com/openregister/deployment/commit/4b9276c718aab320ec50b6364687f1b0c538a670

### CODE REVIEW

**Comment by philandstuff** [comment]
Can I just check I understand correctly?

If I merge, then the effect will be:

 - multi register instances will be unchanged, as they were already set up in 4b9276c
 - bastions will be reprovisioned to the new AMI
 - no other changes

right?

**Comment by samcrang** [comment]
And "address" in test will need rebuilding, but otherwise that's what I expect, yes.

**Comment by philandstuff** [comment]
so... I can't run `make plan` on this as I don't have tf 0.8.0 😢  can someone else review and merge?

**Comment by samcrang** [comment]
This will merge cleanly but it needs updating because we've added additional explicit references to the new AMI (rather then just falling back to the default which this PR is meant to change).

Please don't merge yet.

**Comment by samcrang** [comment]
This is ready to merge again.

**Comment by samcrang** [comment]
Please don't merge this before #249 has been deployed.

**Comment by samcrang** [comment]
This is ready to merge.

**Comment by karlbaker02** [comment]
👍

**Pull request merged**
